>    1) Write a program to create a 5 dimensional array with all zeros and ones

In [1]:
import numpy as np

In [16]:
x = np.zeros((2,2,2,2,2))

print(x)

[[[[[0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]]]


  [[[0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]]]]



 [[[[0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]]]


  [[[0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]]]]]


In [17]:
x = np.ones((2,2,2,2,2))
print(x)

[[[[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]


  [[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]]



 [[[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]


  [[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]]]


2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

In [40]:
x = np.array([np.zeros(10), np.ones(10), np.full(10,5)])



print(x)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


3) Write a program to create a 3x4 matrix filled with values from 10 to 21.


In [41]:
x = np.arange(10,22).reshape(3,4)
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,


In [48]:
x = np.zeros((10, 10))

print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [49]:
zero_to_nine = np.diag(np.arange(10))
print(zero_to_nine)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


5) Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.


In [61]:

x = np.arange(1,17).reshape(4,4)

print(x)

swapped_array = x[:, [3, 2, 1, 0]]

print(swapped_array)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


6) Write a program to reverse an array (the first element becomes the last).
Given array:[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [70]:
x = np.arange(12,28)
print(x)
reverse_element = x[::-1]
print(reverse_element)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
[27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [80]:
x = np.arange(1,101).reshape(10,10)
print(x)
y = x[np.where((x > 30) & (x < 80) & (x % 5 == 0))]
print('\n', y)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

 [35 40 45 50 55 60 65 70 75]


11) Write a program to create an array 2d array and then reshape into 1d array

In [105]:
x = np.arange(1,5).reshape(2,2)
print(x)
y = x.reshape(-1)
print('\n', y)

[[1 2]
 [3 4]]

 [1 2 3 4]
