In [13]:
import numpy as np
from scipy import stats

In [14]:
from numpy import genfromtxt

In [15]:
fpath = ("Sample_data.csv")

In [16]:
data = np.genfromtxt(fpath,delimiter = ',',skip_header = True)
print(data)

[[ 0. 25. 40.]
 [ 1. 30. 35.]
 [ 2. 28. 38.]
 [ 3. 32. 41.]
 [ 4. 26. 37.]
 [ 5. 29. 36.]
 [ 6. 27. 39.]
 [ 7. 33. 42.]
 [ 8. 31. 38.]
 [ 9. 28. 37.]
 [10. 30. 40.]
 [11. 29. 36.]]


### 1)1. Calculate the mean sales for Product A and Product B. Compare the average monthly sales for the two products and discuss any observed trends.

In [17]:
product_A=data[:,1]
product_A

array([25., 30., 28., 32., 26., 29., 27., 33., 31., 28., 30., 29.])

In [18]:
product_B=data[:,2]
product_B

array([40., 35., 38., 41., 37., 36., 39., 42., 38., 37., 40., 36.])

In [19]:
mean_A =np.mean(product_A)
mean_B =np.mean(product_B)

print(f"Mean sales for Product A: {mean_A}")
print(f"Mean sales for Product A: {mean_B}")

Mean sales for Product A: 29.0
Mean sales for Product A: 38.25


### 2) Find the median sales for each product and discuss how it reflects the central tendency of the sales distribution.

In [20]:
median_A =np.median(product_A)
median_B = np.median(product_B)

print(f"Median sales for Product A: {median_A}")
print(f"Median sales for Product A: {median_B}")

Median sales for Product A: 29.0
Median sales for Product A: 38.0


### 3)Identify the mode of the sales data for both Product A and Product B. Discuss the significance of the mode in the context of these products.

In [35]:
mode_product_A = stats.mode(product_A)
mode_product_B = stats.mode(product_B)

print(f"mode sales for Product A: {mode_product_A}")
print(f"mode sales for Product A: {mode_product_B}")

mode sales for Product A: ModeResult(mode=28.0, count=2)
mode sales for Product A: ModeResult(mode=36.0, count=2)


In [37]:
import statistics
x = statistics.mode(product_A)
y = statistics.mode(product_B)

print(f"mode sales for Product A: {x}")
print(f"mode sales for Product A: {y}")

mode sales for Product A: 30.0
mode sales for Product A: 40.0


### 4) Calculate the weighted mean of the sales data, assuming each month has an equal weight. Discuss any implications of using weighted mean in this context.


In [38]:
weighted_mean_A =np.mean(product_A)
weighted_mean_B =np.mean(product_B)

print(f"Mean sales for Product A: {weighted_mean_A}")
print(f"Mean sales for Product A: {weighted_mean_B}")

Mean sales for Product A: 29.0
Mean sales for Product A: 38.25


## Measures of Dispersion:

### 1. Compute the range of monthly sales for both Product A and Product B. Discuss how the range provides insights into the variability of sales.

In [41]:
print(product_A)
print(product_B)

[25. 30. 28. 32. 26. 29. 27. 33. 31. 28. 30. 29.]
[40. 35. 38. 41. 37. 36. 39. 42. 38. 37. 40. 36.]


In [42]:
range_A = np.max(product_A) - np.min(product_A)
range_B = np.max(product_B) - np.min(product_B)

print(f"range of monthly sales for Product A : {range_A}")
print(f"range of monthly sales for Product A : {range_B}")

range of monthly sales for Product A : 8.0
range of monthly sales for Product A : 7.0


### 2. Calculate the variance of the sales data for both products. Discuss what the variance reveals about the spread of sales for each product.

In [43]:
variance_A = np.var(product_A)
variance_B = np.var(product_B)

print(f"variance of the sales for Product A : {variance_A}")
print(f"variance of the sales for Product A : {variance_B}")

variance of the sales for Product A : 5.166666666666667
variance of the sales for Product A : 4.354166666666667


### 3. Determine the standard deviation of the sales for Product A and Product B. Discuss the significance of standard deviation in understanding the variability in sales.

In [45]:
standard_deviation_A = np.std(product_A)
standard_deviation_B = np.std(product_B)

print(f"standard variance of  sales for Product A : {standard_deviation_A}")
print(f"standard variance of  sales for Product A : {standard_deviation_B}")

standard variance of  sales for Product A : 2.273030282830976
standard variance of  sales for Product A : 2.0866640042581523


# Relative Measures of Dispersion:

### 1. Calculate the coefficient of variation for the sales data of Product A. Discuss how this relative measure of dispersion helps in comparing the variability of products with different average sales.

In [48]:
coefficient_A = (standard_deviation_A / mean_A) * 100
print(f"coefficient variation of sales Product A : {coefficient_A}")

coefficient variation of sales Product A : 7.838035458037848


### 2. Compute the relative range for Product B. Discuss how the relative range accounts for the scale of the sales data.

In [51]:
realtive_range_B = (range_B / mean_B) * 100
print(f"Relative Range for sales Product B : {realtive_range_B}")

Relative Range for sales Product B : 18.30065359477124


### 3. Determine the relative standard deviation for Product A. Interpret the result and discuss its implications for understanding the variability relative to the mean.

In [52]:
realtive_standard_devation_A = (standard_deviation_A / mean_A) *100
print(f"realtive standard devation for sales Product A : {realtive_standard_devation_A}")

realtive standard devation for sales Product A : 7.838035458037848
