In [171]:
import numpy as np

In [172]:
from numpy import genfromtxt

In [235]:
fpath = ("tipsf.csv")

In [236]:
data = np.genfromtxt(fpath,delimiter = ',',skip_header = True)
print(data)

[[0.00 16.99 1.01 ... 1.00 0.00 2.00]
 [1.00 10.34 1.66 ... 1.00 0.00 3.00]
 [2.00 21.01 3.50 ... 1.00 0.00 3.00]
 ...
 [241.00 22.67 2.00 ... 0.00 0.00 2.00]
 [242.00 17.82 1.75 ... 0.00 0.00 2.00]
 [243.00 18.78 3.00 ... 2.00 0.00 2.00]]


-  To Calculate the total bill Value.

In [253]:
data[:,1].sum() 

4827.77

- To Calculate the total tip Value

In [238]:
data[:,2].sum() # Total tip value

731.5799999999999

- Total Number of days

In [239]:
np.unique(data[:,5], return_counts=True) # Total NO.Of days(sun, sat, thu, fri)

(array([0.00, 1.00, 2.00, 3.00]), array([87, 76, 62, 19], dtype=int64))

In [240]:
sun_sat_fri_thu = data[:, 5]

unique_values, counts = np.unique(sun_sat_fri_thu, return_counts=True)

for value, count in zip(unique_values, counts):
    print(f"Number Of {value}: {count}")



Number Of 0.0: 87
Number Of 1.0: 76
Number Of 2.0: 62
Number Of 3.0: 19


-  How many smokers:

In [241]:
smokers = data[:, 4]

unique_values, counts = np.unique(smokers, return_counts=True) #

for value, count in zip(unique_values, counts):
    print(f"Number Of {value}: {count}")

Number Of 0.0: 151
Number Of 1.0: 93


In [242]:
data[:,4].sum() # Total Number Of smokers.

93.0

-  Average tip by Male and Female:

In [243]:
tip =data[:,2]
sex =data[:,3]
tip_male = np.mean(tip[sex == 0])
print("Average tip for males:", tip_male)
tip_female = np.mean(tip[sex == 1])
print("Average tip for males:", tip_female)

Average tip for males: 2.8334482758620685
Average tip for males: 3.0896178343949043


-  Total bill value Male and Female

In [252]:
tip = data[:, 2]
amount =data[:,1]
sex =data[:,3]
total = np.sum(amount[sex == 0])
tip_male = np.sum(tip[sex == 0])
total_amount_male = total + tip_male
print("Total Amount Spent by males:", total_amount_male)# AMount spent by male and female
total = np.sum(amount[sex == 1])
tip_female = np.sum(tip[sex == 1])
total_amount_female = total + tip_female
print("Total Amount Spent by Female:", total_amount_female)

Total Amount Spent by males: 1817.4599999999996
Total Amount Spent by Female: 3741.89


- Maxium and Minimum tip

In [219]:
tip = data[:, 2]
x = np.min(tip)
print("Minimum Tip:", x)
y = np.max(tip)
print("Maximum Tip:", y)

Minimum Tip: 1.0
Maximum Tip: 10.0


-  Male and Female Lunch, Dinner

In [226]:
gender = data[:,3]
time = data[:,6]
male_lunch = np.sum((gender == 0) & (time == 1))
female_lunch = np.sum((gender == 1) & (time == 1))
male_lunch = np.sum((gender == 0) & (time == 0))
female_lunch = np.sum((gender == 1) & (time == 0))
print("No of male lunch:", male_lunch )
print("No of female lunch:",female_lunch)
print("No of male Dinner:", male_lunch )
print("No of female Dinner:",female_lunch)

No of male lunch: 52
No of female lunch: 124
No of male Dinner: 52
No of female Dinner: 124


- Average value of size

In [231]:
size = data[:, 7]
np.mean(size)


2.569672131147541

- Number of smokers male and female:

In [232]:
smoker = data[:, 4]
gender = data[:, 3]
x= np.sum((gender == 0) & (smoker == 1))
y = np.sum((gender == 1) & (smoker == 1))
print("No of male smokers:", x)
print("No of female smokers:", y)

No of male smokers: 33
No of female smokers: 60
